# Generated by Django 4.1.7 on 2023-08-05 08:32

import account.models
from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('private_metadata', models.JSONField(blank=True, default=dict)),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('profile_img', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_images')),
                ('phone_number', account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None)),
                ('login_points', models.PositiveIntegerField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Account Verification Token')),
                ('verification_token_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Verification Token Expiration')),
                ('reset_password_token', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Password Token')),
                ('reset_password_token_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Password Token Expiration')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese')], default='en', max_length=35)),
                ('note', models.TextField(blank=True, null=True)),
                ('search_document', models.TextField(blank=True, default='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CheckInHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_window', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('event_type', models.CharField(choices=[('ACCESS_TOKEN_GENERATED', 'access_token_generated'), ('ACCESS_TOKEN_INVALIDATED', 'access_token_invalidated'), ('ACCESS_TOKEN_EXPIRED', 'access_token_expired'), ('REFRESH_TOKEN_GENERATED', 'refresh_token_generated'), ('REFRESH_TOKEN_EXPIRED', 'refresh_token_expired'), ('SIGNUP_ATTEMPT', 'signup_attempt'), ('SIGNUP_ATTEMPT_FAILED', 'signup_attempt_failed'), ('ACCOUNT_CREATED', 'account_created'), ('ADMIN_ACCOUNT_CREATED', 'admin_account_created'), ('ACCOUNT_VERIFIED', 'account_verified'), ('ADMIN_ACCOUNT_VERIFIED', 'admin_account_verified'), ('ACCOUNT_DEACTIVATED', 'account_deactivated'), ('ACCOUNT_REACTIVATED', 'account_reactivated'), ('ACCOUNT_SUSPENDED', 'account_suspended'), ('ACCOUNT_LINKED_TO_GOOGLE', 'account_linked_to_google'), ('ACCOUNT_LINKED_TO_FACEBOOK', 'account_linked_to_facebook'), ('ACCOUNT_LINKED_TO_TWITTER', 'account_linked_to_twitter'), ('EMAIL_CHANGE_REQUEST', 'email_change_request'), ('EMAIL_CHANGED_BY_USER', 'email_changed_by_user'), ('EMAIL_CHANGED_BY_ADMIN', 'email_changed_by_admin'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET_BY_USER', 'password_reset_by_user'), ('PASSWORD_CHANGED', 'password_changed'), ('PHONE_CHANGE_REQUEST', 'phone_change_request'), ('PHONE_CHANGED_BY_USER', 'phone_changed_by_user'), ('USER_PHONE_CHANGED_BY_ADMIN', 'user_phone_changed_by_admin'), ('LOGIN_ATTEMPT', 'login_attempt'), ('FAILED_LOGIN_ATTEMPT', 'failed_login_attempt'), ('SUCCESSFUL_LOGIN', 'successful_login'), ('SUCCESFULL_LOGOUT', 'succesfull_logout'), ('TWO_FACTOR_ENABLED', 'two_factor_enabled'), ('TWO_FACTOR_DISABLED', 'two_factor_disabled'), ('TWO_FACTOR_CODE_SENT', 'two_factor_code_sent'), ('TWO_FACTOR_CODE_RESENT', 'two_factor_code_resent'), ('TWO_FACTOR_CODE_EXPIRED', 'two_factor_code_expired'), ('TWO_FACTOR_FAILED', 'two_factor_failed'), ('TWO_FACTOR_SUCCESS', 'two_factor_success'), ('VERIFICATION_EMAIL_REQUESTED', 'verification_email_requested'), ('VERIFICATION_EMAIL_SENT', 'verification_email_sent')], max_length=255, verbose_name='Event type')),
                ('payload', models.JSONField(blank=True, default=dict, null=True, verbose_name='Event parameters')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('restricted_access_to_channels', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            managers=[
                ('objects', account.models.GroupManager()),
            ],
        ),
    ]
