# Generated by Django 4.1.7 on 2023-06-11 06:02

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_login_points_checkinhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('restricted_access_to_channels', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            managers=[
                ('objects', account.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('email',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='user_addresses', to='account.address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese')], default='en', max_length=35),
        ),
        migrations.AddField(
            model_name='customuser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='private_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customerevent',
            name='event_type',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'account_created'), ('ACCOUNT_ACTIVATED', 'account_activated'), ('ACCOUNT_DEACTIVATED', 'account_deactivated'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET', 'password_reset'), ('PASSWORD_CHANGED', 'password_changed'), ('PHONE_CHANGE_REQUEST', 'phone_change_request'), ('PHONE_CHANGED', 'phone_changed'), ('EMAIL_CHANGE_REQUEST', 'email_change_request'), ('EMAIL_CHANGED', 'email_changed'), ('VERIFICATION_EMAIL_SENT', 'verification_email_sent'), ('CUSTOMER_DELETED', 'customer_deleted'), ('NAME_ASSIGNED', 'name_assigned'), ('EMAIL_ASSIGNED', 'email_assigned'), ('NOTE_ADDED_TO_ORDER', 'note_added_to_order'), ('CURRENCY_WITHDRAWAL', 'currency_withdrawal'), ('CURRENCY_DEPOSIT', 'currency_deposit'), ('PLACED_SINGLE_ORDER', 'placed_single_order'), ('PLACED_BUNDLE_ORDER', 'placed_bundle_order'), ('PLACED_TOPUP_ORDER', 'placed_topup_order'), ('WATCHED_ADS_IN_PLATFORM', 'watched_ads_in_platform'), ('USED_PROMO_CODE', 'used_promo_code')], max_length=255, verbose_name='Event type'),
        ),
    ]
