# Generated by Django 4.1.7 on 2023-06-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_group_alter_customuser_options_customuser_addresses_and_more'),
        ('permission', '0001_initial'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='permission.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='group',
            name='channels',
            field=models.ManyToManyField(blank=True, to='channel.channel'),
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='permission.permission', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='account.group', verbose_name='groups'),
        ),
    ]
