# Generated by Django 4.1.7 on 2023-06-11 06:31

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_user_permissions_group_channels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None),
        ),
    ]
