# Generated by Django 4.1.7 on 2023-06-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customuser_jwt_token_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
