# Generated by Django 4.1.7 on 2023-07-30 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_customerevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jwt_token_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Password Token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Password Token Expiration'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Account Verification Token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Token Expiration'),
        ),
        migrations.AlterField(
            model_name='customerevent',
            name='event_type',
            field=models.CharField(choices=[('USER_SIGNUP', 'user_signup'), ('USER_ACCOUNT_VERIFIED', 'user_account_verified'), ('USER_LOGIN_ATTEMPT', 'user_login_attempt'), ('USER_LOGIN_FAILED', 'user_login_failed'), ('USER_LOGIN_SUCCESSFUL', 'user_login_successful'), ('USER_ACCOUNT_DEACTIVATED', 'user_account_deactivated'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET', 'password_reset'), ('PASSWORD_CHANGED', 'password_changed'), ('PHONE_CHANGE_REQUEST', 'phone_change_request'), ('PHONE_CHANGED', 'phone_changed'), ('EMAIL_CHANGE_REQUEST', 'email_change_request'), ('EMAIL_CHANGED', 'email_changed'), ('VERIFICATION_EMAIL_SENT', 'verification_email_sent'), ('NEW_VERIFICATION_EMAIL_REQUESTED', 'new_verification_email_requested'), ('NEW_VERIFICATION_EMAIL_SENT', 'new_verification_email_sent'), ('CUSTOMER_DELETED', 'customer_deleted'), ('NAME_ASSIGNED', 'name_assigned'), ('EMAIL_ASSIGNED', 'email_assigned'), ('NOTE_ADDED_TO_ORDER', 'note_added_to_order'), ('CURRENCY_WITHDRAWAL', 'currency_withdrawal'), ('CURRENCY_DEPOSIT', 'currency_deposit'), ('PLACED_SINGLE_ORDER', 'placed_single_order'), ('PLACED_BUNDLE_ORDER', 'placed_bundle_order'), ('PLACED_TOPUP_ORDER', 'placed_topup_order'), ('WATCHED_ADS_IN_PLATFORM', 'watched_ads_in_platform'), ('USED_PROMO_CODE', 'used_promo_code')], max_length=255, verbose_name='Event type'),
        ),
    ]
