# Generated by Django 4.1.7 on 2023-07-30 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_customuser_jwt_token_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerevent',
            name='event_type',
            field=models.CharField(choices=[('ACCESS_TOKEN_GENERATED', 'access_token_generated'), ('ACCESS_TOKEN_INVALIDATED', 'access_token_invalidated'), ('ACCESS_TOKEN_EXPIRED', 'access_token_expired'), ('REFRESH_TOKEN_GENERATED', 'refresh_token_generated'), ('REFRESH_TOKEN_EXPIRED', 'refresh_token_expired'), ('SIGNUP_ATTEMPT', 'signup_attempt'), ('SIGNUP_ATTEMPT_FAILED', 'signup_attempt_failed'), ('ACCOUNT_CREATED', 'account_created'), ('ADMIN_ACCOUNT_CREATED', 'admin_account_created'), ('ACCOUNT_VERIFIED', 'account_verified'), ('ADMIN_ACCOUNT_VERIFIED', 'admin_account_verified'), ('ACCOUNT_DEACTIVATED', 'account_deactivated'), ('ACCOUNT_REACTIVATED', 'account_reactivated'), ('ACCOUNT_SUSPENDED', 'account_suspended'), ('ACCOUNT_LINKED_TO_GOOGLE', 'account_linked_to_google'), ('ACCOUNT_LINKED_TO_FACEBOOK', 'account_linked_to_facebook'), ('ACCOUNT_LINKED_TO_TWITTER', 'account_linked_to_twitter'), ('EMAIL_CHANGE_REQUEST', 'email_change_request'), ('EMAIL_CHANGED_BY_USER', 'email_changed_by_user'), ('EMAIL_CHANGED_BY_ADMIN', 'email_changed_by_admin'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET_BY_USER', 'password_reset_by_user'), ('PASSWORD_CHANGED', 'password_changed'), ('PHONE_CHANGE_REQUEST', 'phone_change_request'), ('PHONE_CHANGED_BY_USER', 'phone_changed_by_user'), ('USER_PHONE_CHANGED_BY_ADMIN', 'user_phone_changed_by_admin'), ('LOGIN_ATTEMPT', 'login_attempt'), ('FAILED_LOGIN_ATTEMPT', 'failed_login_attempt'), ('SUCCESSFUL_LOGIN', 'successful_login'), ('SUCCESFULL_LOGOUT', 'succesfull_logout'), ('TWO_FACTOR_ENABLED', 'two_factor_enabled'), ('TWO_FACTOR_DISABLED', 'two_factor_disabled'), ('TWO_FACTOR_CODE_SENT', 'two_factor_code_sent'), ('TWO_FACTOR_CODE_RESENT', 'two_factor_code_resent'), ('TWO_FACTOR_CODE_EXPIRED', 'two_factor_code_expired'), ('TWO_FACTOR_FAILED', 'two_factor_failed'), ('TWO_FACTOR_SUCCESS', 'two_factor_success'), ('VERIFICATION_EMAIL_REQUESTED', 'verification_email_requested'), ('VERIFICATION_EMAIL_SENT', 'verification_email_sent')], max_length=255, verbose_name='Event type'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACCESS_TOKEN_GENERATED', 'access_token_generated'), ('ACCESS_TOKEN_INVALIDATED', 'access_token_invalidated'), ('ACCESS_TOKEN_EXPIRED', 'access_token_expired'), ('REFRESH_TOKEN_GENERATED', 'refresh_token_generated'), ('REFRESH_TOKEN_EXPIRED', 'refresh_token_expired'), ('SIGNUP_ATTEMPT', 'signup_attempt'), ('SIGNUP_ATTEMPT_FAILED', 'signup_attempt_failed'), ('ACCOUNT_CREATED', 'account_created'), ('ADMIN_ACCOUNT_CREATED', 'admin_account_created'), ('ACCOUNT_VERIFIED', 'account_verified'), ('ADMIN_ACCOUNT_VERIFIED', 'admin_account_verified'), ('ACCOUNT_DEACTIVATED', 'account_deactivated'), ('ACCOUNT_REACTIVATED', 'account_reactivated'), ('ACCOUNT_SUSPENDED', 'account_suspended'), ('ACCOUNT_LINKED_TO_GOOGLE', 'account_linked_to_google'), ('ACCOUNT_LINKED_TO_FACEBOOK', 'account_linked_to_facebook'), ('ACCOUNT_LINKED_TO_TWITTER', 'account_linked_to_twitter'), ('EMAIL_CHANGE_REQUEST', 'email_change_request'), ('EMAIL_CHANGED_BY_USER', 'email_changed_by_user'), ('EMAIL_CHANGED_BY_ADMIN', 'email_changed_by_admin'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET_BY_USER', 'password_reset_by_user'), ('PASSWORD_CHANGED', 'password_changed'), ('PHONE_CHANGE_REQUEST', 'phone_change_request'), ('PHONE_CHANGED_BY_USER', 'phone_changed_by_user'), ('USER_PHONE_CHANGED_BY_ADMIN', 'user_phone_changed_by_admin'), ('LOGIN_ATTEMPT', 'login_attempt'), ('FAILED_LOGIN_ATTEMPT', 'failed_login_attempt'), ('SUCCESSFUL_LOGIN', 'successful_login'), ('SUCCESFULL_LOGOUT', 'succesfull_logout'), ('TWO_FACTOR_ENABLED', 'two_factor_enabled'), ('TWO_FACTOR_DISABLED', 'two_factor_disabled'), ('TWO_FACTOR_CODE_SENT', 'two_factor_code_sent'), ('TWO_FACTOR_CODE_RESENT', 'two_factor_code_resent'), ('TWO_FACTOR_CODE_EXPIRED', 'two_factor_code_expired'), ('TWO_FACTOR_FAILED', 'two_factor_failed'), ('TWO_FACTOR_SUCCESS', 'two_factor_success'), ('VERIFICATION_EMAIL_REQUESTED', 'verification_email_requested'), ('VERIFICATION_EMAIL_SENT', 'verification_email_sent')], max_length=255, verbose_name='Event type')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User activity',
                'verbose_name_plural': 'User activities',
                'ordering': ('-timestamp',),
            },
        ),
    ]
