# Generated by Django 4.1.7 on 2023-07-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_customerevent_event_type_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
