# Generated by Django 4.1.7 on 2023-07-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_delete_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerevent',
            old_name='parameters',
            new_name='payload',
        ),
    ]
