# Generated by Django 4.1.7 on 2023-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_parameters_customerevent_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Event parameters'),
        ),
    ]
