# Generated by Django 4.1.7 on 2023-09-08 05:03

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='League Name')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball')], default='football', max_length=255, verbose_name='Sport')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('year', models.IntegerField(default=2023, verbose_name='Year')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Team Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos', verbose_name='Team Logo')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball')], default='football', max_length=255, verbose_name='Sport')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.league')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Player Name')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FW', 'Forward')], max_length=3, verbose_name='Position')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('jersey_number', models.PositiveIntegerField(verbose_name='Jersey Number')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='player_pictures')),
                ('slug', models.SlugField(blank=True, help_text='Label for URL configuration', max_length=155, null=True, unique=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sports.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['name'],
            },
        ),
    ]
