# Generated by Django 4.1.7 on 2023-08-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Team Name'),
        ),
    ]
