# Generated by Django 4.1.7 on 2023-08-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_team_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
    ]
