# Generated by Django 4.1.7 on 2023-08-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_team_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Year'),
        ),
    ]
