# Generated by Django 4.1.7 on 2023-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('event_type', models.CharField(choices=[('auction_created', 'Auction created'), ('auction_ended', 'Auction ended'), ('auction_cancelled', 'Auction cancelled'), ('bid_placed', 'Bid placed'), ('auction_reported', 'Auction reported'), ('auction_followed', 'Auction followed'), ('auction_unfollowed', 'Auction unfollowed'), ('auction_sold', 'Auction sold'), ('auction_not_sold', 'Auction not sold')], max_length=255, verbose_name='Event type')),
                ('auction_id', models.IntegerField(blank=True, null=True, verbose_name='Auction ID')),
                ('payload', models.JSONField(blank=True, default=dict, null=True, verbose_name='Event parameters')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('event_type', models.CharField(choices=[('access_token_generated', 'Access token generated'), ('access_token_invalidated', 'Access token invalidated'), ('access_token_expired', 'Access token expired'), ('refresh_token_generated', 'Refresh token generated'), ('refresh_token_expired', 'Refresh token expired'), ('signup_attempt', 'Signup attempt'), ('signup_attempt_failed', 'Signup attempt failed'), ('signup_attempt_successful', 'Signup attempt successful'), ('account_created', 'Account created'), ('admin_account_created', 'Admin account created'), ('account_verified', 'Account verified'), ('admin_account_verified', 'Admin account verified'), ('account_deactivated', 'Account deactivated'), ('account_reactivated', 'Account reactivated'), ('account_suspended', 'Account suspended'), ('account_linked_to_google', 'Account linked to Google'), ('email_change_request', 'Email change requested'), ('email_changed_by_user', 'Email changed by user'), ('email_changed_by_admin', 'User email changed by admin'), ('password_reset_request', 'Password reset request'), ('password_reset_link_sent', 'Password reset link sent'), ('password_reset_by_user', 'Password reset by user'), ('password_changed', 'Password changed'), ('phone_change_request', 'Phone change requested'), ('phone_changed_by_user', 'Phone changed by user'), ('user_phone_changed_by_admin', 'User phone changed by admin'), ('login_attempt', 'Login attempt'), ('failed_login_attempt', 'Failed login attempt'), ('successful_login', 'Successful login'), ('succesfull_logout', 'Succesfull logout'), ('two_factor_enabled', 'Two factor enabled'), ('two_factor_disabled', 'Two factor disabled'), ('two_factor_code_sent', 'Two factor code sent'), ('two_factor_code_resent', 'Two factor code resent'), ('two_factor_failed', 'Two factor failed'), ('two_factor_success', 'Two factor success'), ('verification_email_requested', 'Verification email requested'), ('verification_email_sent', 'Verification email sent')], max_length=255, verbose_name='Event type')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User ID')),
                ('payload', models.JSONField(blank=True, default=dict, null=True, verbose_name='Event parameters')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='InAppCurrencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('event_type', models.CharField(choices=[('in_app_currency_purchased', 'In app currency purchased'), ('in_app_currency_purchase_failed', 'In app currency purchase failed'), ('in_app_currency_purchase_refunded', 'In app currency purchase refunded'), ('in_app_currency_purchase_reversed', 'In app currency purchase reversed'), ('in_app_currency_purchase_reversal_failed', 'In app currency purchase reversal failed')], max_length=255, verbose_name='Event type')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User ID')),
                ('payload', models.JSONField(blank=True, default=dict, null=True, verbose_name='Event parameters')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
