# Generated by Django 4.1.7 on 2023-09-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('receive_email_updates', models.BooleanField(default=True)),
                ('receive_player_available_updates', models.BooleanField(default=True)),
                ('receive_outbid_updates', models.BooleanField(default=True)),
                ('receive_winning_updates', models.BooleanField(default=True)),
                ('receive_purchase_updates', models.BooleanField(default=True)),
                ('receive_sale_updates', models.BooleanField(default=True)),
                ('receive_failed_sale_updates', models.BooleanField(default=True)),
                ('receive_offer_updates', models.BooleanField(default=True)),
                ('receive_reward_updates', models.BooleanField(default=True)),
                ('receive_referral_updates', models.BooleanField(default=True)),
                ('receive_loyalty_updates', models.BooleanField(default=True)),
                ('receive_birthday_updates', models.BooleanField(default=True)),
                ('receive_milestone_updates', models.BooleanField(default=True)),
                ('receive_collection_updates', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
