# Generated by Django 4.1.7 on 2023-09-08 05:03

import custom_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('private_metadata', models.JSONField(blank=True, default=dict)),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('profile_img', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_images')),
                ('phone_number', custom_user.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None)),
                ('login_points', models.PositiveIntegerField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Account Verification Token')),
                ('verification_token_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Verification Token Expiration')),
                ('reset_password_token', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Password Token')),
                ('reset_password_token_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Password Token Expiration')),
                ('auth_provider', models.CharField(default='email', max_length=255)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese')], default='en', max_length=35)),
                ('note', models.TextField(blank=True, null=True)),
                ('search_document', models.TextField(blank=True, default='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('reserved_balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('restricted_access_to_channels', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(blank=True, to='permission.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            managers=[
                ('objects', custom_user.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('event_type', models.CharField(choices=[('access_token_generated', 'Access token generated'), ('access_token_invalidated', 'Access token invalidated'), ('access_token_expired', 'Access token expired'), ('refresh_token_generated', 'Refresh token generated'), ('refresh_token_expired', 'Refresh token expired'), ('signup_attempt', 'Signup attempt'), ('signup_attempt_failed', 'Signup attempt failed'), ('signup_attempt_successful', 'Signup attempt successful'), ('account_created', 'Account created'), ('admin_account_created', 'Admin account created'), ('account_verified', 'Account verified'), ('admin_account_verified', 'Admin account verified'), ('account_deactivated', 'Account deactivated'), ('account_reactivated', 'Account reactivated'), ('account_suspended', 'Account suspended'), ('account_linked_to_google', 'Account linked to Google'), ('account_linked_to_facebook', 'Account linked to Facebook'), ('account_linked_to_twitter', 'Account linked to Twitter'), ('email_change_request', 'Email change requested'), ('email_changed_by_user', 'Email changed by user'), ('email_changed_by_admin', 'User email changed by admin'), ('password_reset_link_sent', 'Password reset link sent'), ('password_reset_by_user', 'Password reset by user'), ('password_changed', 'Password changed'), ('phone_change_request', 'Phone change requested'), ('phone_changed_by_user', 'Phone changed by user'), ('user_phone_changed_by_admin', 'User phone changed by admin'), ('login_attempt', 'Login attempt'), ('failed_login_attempt', 'Failed login attempt'), ('successful_login', 'Successful login'), ('succesfull_logout', 'Succesfull logout'), ('two_factor_enabled', 'Two factor enabled'), ('two_factor_disabled', 'Two factor disabled'), ('two_factor_code_sent', 'Two factor code sent'), ('two_factor_code_resent', 'Two factor code resent'), ('two_factor_code_expired', 'Two factor code expired'), ('two_factor_failed', 'Two factor failed'), ('two_factor_success', 'Two factor success'), ('verification_email_requested', 'Verification email requested'), ('verification_email_sent', 'Verification email sent')], max_length=255, verbose_name='Event type')),
                ('payload', models.JSONField(blank=True, default=dict, null=True, verbose_name='Event parameters')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='CheckInHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_window', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['first_name', 'last_name'], name='custom_user_first_n_5bc0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address'], name='custom_user_address_757d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='custom_user_city_729057_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state'], name='custom_user_state_5ab3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country'], name='custom_user_country_3c1cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code'], name='custom_user_postal__12aee8_idx'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='user_addresses', to='custom_user.address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_user.address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='custom_user.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='permission.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='custom_user_usernam_47c2da_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='custom_user_email_8a7a66_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='custom_user_phone_n_730071_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['country'], name='custom_user_country_71662f_idx'),
        ),
    ]
