# Generated by Django 4.1.7 on 2023-09-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerevent',
            name='user',
        ),
        migrations.AddField(
            model_name='customerevent',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
