# Generated by Django 4.1.7 on 2023-08-21 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='permission.permission', verbose_name='permissions'),
        ),
        migrations.AddField(
            model_name='customerevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkinhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['first_name', 'last_name'], name='custom_user_first_n_5bc0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address'], name='custom_user_address_757d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='custom_user_city_729057_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state'], name='custom_user_state_5ab3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country'], name='custom_user_country_3c1cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code'], name='custom_user_postal__12aee8_idx'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='user_addresses', to='custom_user.address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_user.address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='custom_user.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='permission.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='custom_user_usernam_47c2da_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='custom_user_email_8a7a66_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='custom_user_phone_n_730071_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['country'], name='custom_user_country_71662f_idx'),
        ),
    ]
