# Generated by Django 4.1.7 on 2023-09-12 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_remove_customerevent_user_customerevent_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerevent',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customerevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
