# Generated by Django 4.1.7 on 2023-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_remove_customerevent_user_id_customerevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerevent',
            name='event_type',
            field=models.CharField(choices=[('access_token_generated', 'Access token generated'), ('access_token_invalidated', 'Access token invalidated'), ('access_token_expired', 'Access token expired'), ('refresh_token_generated', 'Refresh token generated'), ('refresh_token_expired', 'Refresh token expired'), ('signup_attempt', 'Signup attempt'), ('signup_attempt_failed', 'Signup attempt failed'), ('signup_attempt_successful', 'Signup attempt successful'), ('account_created', 'Account created'), ('admin_account_created', 'Admin account created'), ('account_verified', 'Account verified'), ('admin_account_verified', 'Admin account verified'), ('account_deactivated', 'Account deactivated'), ('account_reactivated', 'Account reactivated'), ('account_suspended', 'Account suspended'), ('account_linked_to_google', 'Account linked to Google'), ('email_change_request', 'Email change requested'), ('email_changed_by_user', 'Email changed by user'), ('email_changed_by_admin', 'User email changed by admin'), ('password_reset_request', 'Password reset request'), ('password_reset_by_user', 'Password reset by user'), ('password_changed', 'Password changed'), ('phone_change_request', 'Phone change requested'), ('phone_changed_by_user', 'Phone changed by user'), ('user_phone_changed_by_admin', 'User phone changed by admin'), ('login_attempt', 'Login attempt'), ('failed_login_attempt', 'Failed login attempt'), ('successful_login', 'Successful login'), ('succesful_logout', 'Succesfull logout'), ('two_factor_enabled', 'Two factor enabled'), ('two_factor_disabled', 'Two factor disabled'), ('two_factor_code_sent', 'Two factor code sent'), ('two_factor_code_resent', 'Two factor code resent'), ('two_factor_failed', 'Two factor failed'), ('two_factor_success', 'Two factor success'), ('verification_email_requested', 'Verification email requested'), ('verification_email_sent', 'Verification email sent')], max_length=255, verbose_name='Event type'),
        ),
    ]
