# Generated by Django 4.1.7 on 2023-09-15 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_alter_customerevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='addresses',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_user.address'),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_email_updates', models.BooleanField(default=True)),
                ('receive_sms_updates', models.BooleanField(default=True)),
                ('receive_phone_call_updates', models.BooleanField(default=True)),
                ('receive_direct_mail_updates', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
