# Generated by Django 4.1.7 on 2023-08-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerevent',
            name='initiator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
