# Generated by Django 4.1.7 on 2023-09-15 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_remove_customuser_addresses_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='custom_user_first_n_5bc0e3_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user'], name='custom_user_user_id_58d7b0_idx'),
        ),
    ]
