# Generated by Django 4.1.7 on 2023-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_remove_address_custom_user_first_n_5bc0e3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='custom_user_address_757d3a_idx',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street_address'], name='custom_user_street__e2eed2_idx'),
        ),
    ]
