# Generated by Django 4.1.7 on 2023-09-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_remove_address_custom_user_address_757d3a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
