# Generated by Django 4.1.7 on 2023-09-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0010_userpreferences_receive_birthday_updates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='receive_direct_mail_updates',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='receive_phone_call_updates',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='receive_sms_updates',
        ),
    ]
