# Generated by Django 4.1.7 on 2023-09-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0011_remove_userpreferences_receive_direct_mail_updates_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
