# Generated by Django 4.1.7 on 2023-08-05 08:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
                ('starting_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('current_bid', models.PositiveIntegerField(default=0)),
                ('highest_bidder', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('end_time', models.DateTimeField()),
                ('auction_ended', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CardAuctionWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.cardauction')),
            ],
        ),
        migrations.CreateModel(
            name='CardAuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.cardauction')),
            ],
        ),
        migrations.AddField(
            model_name='cardauction',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auction.cardauctionwatcher'),
        ),
        migrations.AddConstraint(
            model_name='cardauction',
            constraint=models.UniqueConstraint(fields=('card_id', 'seller_id', 'start_time'), name='unique_auction'),
        ),
    ]
