# Generated by Django 4.1.7 on 2023-09-08 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardauctionwatcher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardauctionbid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.cardauction'),
        ),
        migrations.AddField(
            model_name='cardauctionbid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardauction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.playercard'),
        ),
        migrations.AddField(
            model_name='cardauction',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardauction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardauction',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auction.cardauctionwatcher'),
        ),
        migrations.AddConstraint(
            model_name='cardauction',
            constraint=models.UniqueConstraint(fields=('card_id', 'seller_id', 'start_time'), name='unique_auction'),
        ),
    ]
