# Generated by Django 4.1.7 on 2023-09-12 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAuctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.PositiveIntegerField()),
                ('winner_id', models.PositiveIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('auction_created', 'Auction created'), ('auction_ended', 'Auction ended'), ('auction_cancelled', 'Auction cancelled'), ('bid_placed', 'Bid placed'), ('bid_rejected', 'Bid rejected'), ('auction_reported', 'Auction reported'), ('auction_report_rejected', 'Auction report rejected'), ('auction_followed', 'Auction followed'), ('auction_unfollowed', 'Auction unfollowed'), ('auction_sold', 'Auction sold'), ('auction_not_sold', 'Auction not sold')], max_length=255)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.cardauction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
