# Generated by Django 4.1.7 on 2023-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_cardauctionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardauctionevent',
            name='event_type',
            field=models.CharField(choices=[('auction_created', 'Auction created'), ('auction_ended', 'Auction ended'), ('auction_cancelled', 'Auction cancelled'), ('bid_placed', 'Bid placed'), ('auction_reported', 'Auction reported'), ('auction_followed', 'Auction followed'), ('auction_unfollowed', 'Auction unfollowed'), ('auction_sold', 'Auction sold'), ('auction_not_sold', 'Auction not sold')], max_length=255),
        ),
    ]
