# Generated by Django 4.1.7 on 2023-08-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('winner_id', models.IntegerField(blank=True, null=True)),
                ('auction_id', models.IntegerField()),
                ('start_price', models.PositiveIntegerField()),
                ('winning_bid', models.PositiveIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('number_of_bids', models.PositiveIntegerField(default=0)),
                ('number_of_watchers', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InAppCurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('currency_package_id', models.IntegerField()),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=100)),
                ('seller_id', models.IntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('card_purchase', 'Card Purchase'), ('bundle_purchase', 'Bundle Purchase')], max_length=50)),
                ('card_id', models.IntegerField(blank=True, null=True)),
                ('bundle_id', models.IntegerField(blank=True, null=True)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
