# Generated by Django 4.1.7 on 2023-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('card_purchase', 'Card Purchase'), ('card_sale', 'Card Sale'), ('bundle_purchase', 'Bundle Purchase')], max_length=50),
        ),
    ]
