# Generated by Django 4.1.7 on 2023-09-08 05:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='bundle_covers/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('buyer_id', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Card Rarity',
                'verbose_name_plural': 'Card Rarities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompletedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_id', models.IntegerField()),
                ('reward_received', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2024', max_length=10, verbose_name='Season')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('number_likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='Index')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('is_locked', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Player Card',
                'verbose_name_plural': 'Player Cards',
            },
        ),
        migrations.CreateModel(
            name='TeamCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cards', models.ManyToManyField(blank=True, to='card.playercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCardLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('playercard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='card.playercard')),
            ],
        ),
    ]
