# Generated by Django 4.1.7 on 2023-08-05 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='bundle_covers/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('buyer_id', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Card Rarity',
                'verbose_name_plural': 'Card Rarities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=255)),
                ('season', models.CharField(default='2024', max_length=10, verbose_name='Season')),
                ('owner_id', models.IntegerField(blank=True, null=True, verbose_name='Owner')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('number_likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='Index')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('is_locked', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='card.cardrarity')),
            ],
            options={
                'verbose_name': 'Player Card',
                'verbose_name_plural': 'Player Cards',
                'ordering': ['player_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('team_id', models.IntegerField()),
                ('reward_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cards', models.ManyToManyField(blank=True, to='card.playercard')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reward_id', models.IntegerField()),
                ('reward_received', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.teamcollection')),
            ],
        ),
        migrations.CreateModel(
            name='BundleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('card_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.bundle')),
                ('player_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.playercard')),
            ],
        ),
        migrations.AddField(
            model_name='bundle',
            name='cards',
            field=models.ManyToManyField(limit_choices_to={'owner_id': None}, through='card.BundleCard', to='card.playercard'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.cardrarity'),
        ),
        migrations.CreateModel(
            name='PlayerCardLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('playercard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='card.playercard')),
            ],
            options={
                'unique_together': {('playercard', 'user_id')},
            },
        ),
        migrations.AddIndex(
            model_name='playercard',
            index=models.Index(fields=['player_name', 'player_id'], name='card_player_player__8c16f0_idx'),
        ),
        migrations.AddIndex(
            model_name='playercard',
            index=models.Index(fields=['owner_id'], name='card_player_owner_i_4cd4bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='completedcollection',
            unique_together={('user_id', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='bundlecard',
            unique_together={('card_bundle', 'player_card')},
        ),
    ]
