# Generated by Django 4.1.7 on 2023-09-08 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        ('card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playercard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.player'),
        ),
        migrations.AddField(
            model_name='playercard',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.cardrarity'),
        ),
        migrations.AddField(
            model_name='completedcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.teamcollection'),
        ),
        migrations.AddField(
            model_name='completedcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundlecard',
            name='card_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.bundle'),
        ),
        migrations.AddField(
            model_name='bundlecard',
            name='player_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.playercard'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='cards',
            field=models.ManyToManyField(limit_choices_to={'owner_id': None}, through='card.BundleCard', to='card.playercard'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.cardrarity'),
        ),
        migrations.AlterUniqueTogether(
            name='playercardlike',
            unique_together={('playercard', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='completedcollection',
            unique_together={('user_id', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='bundlecard',
            unique_together={('card_bundle', 'player_card')},
        ),
    ]
