# Generated by Django 4.1.7 on 2023-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercard',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Value'),
        ),
    ]
