# Generated by Django 4.1.7 on 2023-09-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_playercard_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercard',
            old_name='value',
            new_name='price',
        ),
    ]
