# Generated by Django 4.1.7 on 2023-09-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJOBAReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.PositiveIntegerField(default=500000, help_text='Reward in DJOBA coins')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
