# Generated by Django 4.1.7 on 2023-06-11 06:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('default_country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'ordering': ('slug',),
                'permissions': (('manage_channels', 'Manage channels.'),),
            },
        ),
    ]
