# Generated by Django 4.1.7 on 2023-06-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0016_playercard_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
