# Generated by Django 4.1.7 on 2023-06-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0017_alter_playercard_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercard',
            old_name='id',
            new_name='card_id',
        ),
    ]
